require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/trln_argon/version.rb'

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/trln_argon/helpers/catalog_helper_behavior.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/trln_argon/controller_override.rb'
    - 'lib/tasks/trln_argon_tasks.rake'
    - 'spec/lib/trln_argon/fields_spec.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/trln_argon/install_generator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/trln_argon/helpers/catalog_helper_behavior.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/trln_argon/controller_override.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/trln_argon/helpers/catalog_helper_behavior.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/trln_argon/controller_override.rb'
    - 'lib/trln_argon/fields.rb'
    - 'spec/lib/trln_argon/fields_spec.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/trln_argon/helpers/catalog_helper_behavior.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/routing/catalog_routing_spec.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/catalog_helper_spec.rb'
