inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  # TODO: review this later
  NewCops: disable
  Exclude:
    - '.internal_test_app/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/trln_argon/version.rb'
    - 'lib/trln_argon/item_deserializer.rb'
    - 'trln_argon.gemspec'
    - 'lib/trln_argon/argon_search_builder/add_query_to_solr.rb'
    - 'lib/generators/trln_argon/remove_solr_marc_generator.rb'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'
    - 'lib/trln_argon/view_helpers/hierarchy_helper.rb'
    - 'lib/trln_argon/mappings.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/trln_argon/hathitrust_controller_behavior.rb'
    - 'lib/trln_argon/trln_controller_behavior.rb'
    - 'lib/trln_argon/bookmarks_controller_behavior.rb'
    - 'lib/trln_argon/controller_override.rb'
    - 'lib/tasks/trln_argon_tasks.rake'
    - 'spec/lib/trln_argon/fields_spec.rb'
    - 'spec/**/*'
    - 'config/initializers/trln_argon.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/trln_argon/install_generator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/trln_argon/controller_override.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'
    - 'lib/trln_argon/mappings.rb'
    - 'lib/trln_argon/solr_document/expand_document.rb'
    - 'lib/trln_argon/view_helpers/hierarchy_helper.rb'
    - 'config/initializers/parsing_nesting_parser.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/trln_argon/controller_override.rb'
    - 'lib/trln_argon/fields.rb'
    - 'lib/trln_argon/view_helpers/trln_argon_helper.rb'
    - 'spec/lib/trln_argon/fields_spec.rb'
    - 'lib/trln_argon/view_helpers/items_section_helper.rb'
    - 'lib/trln_argon/solr_document/citation.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/routing/catalog_routing_spec.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/catalog_helper_spec.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive

Style/FrozenStringLiteralComment:
  Enabled: false

# The following were disabled due to an excessive amount of errors
# after an upgrade, not because they're useless.  We can enable them
# one by one over time to avoid excessively large commits
RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/EmptyLineAfterExampleGroup:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Migration/DepartmentName:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false
