require: rubocop-rspec

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'Gemfile'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/trln_argon/version.rb'
    - 'lib/trln_argon/item_deserializer.rb'
    - 'trln_argon.gemspec'
    - 'config/initializers/openurl.rb'
    - 'lib/trln_argon/argon_search_builder/add_query_to_solr.rb'
    - 'lib/generators/trln_argon/remove_solr_marc_generator.rb'

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/trln_argon/trln_controller_behavior.rb'
    - 'lib/trln_argon/bookmarks_controller_behavior.rb'
    - 'lib/trln_argon/controller_override.rb'
    - 'lib/tasks/trln_argon_tasks.rake'
    - 'spec/lib/trln_argon/fields_spec.rb'
    - 'spec/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/generators/trln_argon/install_generator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'lib/trln_argon/controller_override.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'
    - 'lib/trln_argon/mappings.rb'
    - 'lib/trln_argon/solr_document/expand_document.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/trln_argon/controller_override.rb'
    - 'lib/trln_argon/fields.rb'
    - 'lib/trln_argon/view_helpers/trln_argon_helper.rb'
    - 'spec/lib/trln_argon/fields_spec.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/trln_argon/view_helpers/catalog_helper_behavior.rb'

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'
    - 'spec/routing/catalog_routing_spec.rb'

RSpec/ExampleLength:
  Max: 20

RSpec/VerifiedDoubles:
  Exclude:
    - 'spec/helpers/catalog_helper_spec.rb'

RSpec/MessageSpies:
  EnforcedStyle: receive
